import type { Metadata } from "next";
import {
  Inter,
  Montserrat,
  Overpass_Mono,
  Poppins,
} from "next/font/google";
import { headers } from "next/headers";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import {
  defaultLocale,
  isLocale,
  LOCALE_HEADER,
} from "@/lib/i18n-config";
import "./globals.css";
import "./globals.scss";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin", "latin-ext"],
  display: "swap",
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin", "latin-ext"],
  display: "swap",
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin", "latin-ext"],
  display: "swap",
});

const overpassMono = Overpass_Mono({
  variable: "--font-overpass-mono",
  subsets: ["latin", "latin-ext"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerList = await headers();
  const raw = headerList.get(LOCALE_HEADER) ?? defaultLocale;
  const locale = isLocale(raw) ? raw : defaultLocale;
  const dir = locale === "ar" ? "rtl" : "ltr";

  return (
    <html
      lang={locale}
      dir={dir}
      className="light"
      suppressHydrationWarning
    >
      <body
        className={`${inter.variable} ${montserrat.variable} ${poppins.variable} ${overpassMono.variable} antialiased min-h-dvh min-w-0`}
      >
        <AntdRegistry>
          <div className="flex min-h-dvh min-w-0 flex-col gap-section">
            {children}
          </div>
        </AntdRegistry>
      </body>
    </html>
  );
}
